data:
  eval_dir:  s3://ll-coco/datasets/cityscapes
  save_dir: s3://ll-coco/eff/efficient0
  dataset: cityscapes
  batch_size: 2
  input_size: (512, 1024)
  num_classes: -1
  subset: val

seed: 1
compound_coef: 4
weights_path: s3://ll-coco/efficient0/efficient_weights_00000231.pth
weights_dir:
decode_cfg_path: s3://ll-coco/codes/configs/decode_cfg.yaml
trans_cfg_path: s3://ll-coco/codes/configs/trans_cfg.json

