data:
  eval_dir:  C:\data\cityscapes
  save_dir: C:\data\checkpoints\test
  dataset: cityscapes
  batch_size: 2
  input_size: (512, 1024)
  num_classes: -1
  subset: val

seed: 1
model_type: erf
weights_path: C:\data\checkpoints\erf\erf_weights_00000114.pth
weights_dir:  # C:\data\checkpoints\erf
decode_cfg_path: .\configs\decode_cfg.yaml

