data:
  eval_dir:  E:\cityscapes
  save_dir: E:\checkpoints\erf\eval
  dataset: cityscapes
  batch_size: 2
  input_size: (512, 1024)
  num_classes: -1
  subset: val

seed: 1
model_type: erf
weights_path: E:\checkpoints\erf\erf_weights_00000090.pth
weights_dir:  #E:\checkpoints\weights
decode_cfg_path: .\configs\decode_cfg.yaml
trans_cfg_path: .\configs\trans_cfg.json

