data:
  eval_dir:  s3://ll-coco/datasets/cityscapes
  save_dir: s3://ll-coco/checkpoints/eval
  dataset: cityscapes
  batch_size: 16
  num_classes: -1
  subset: val

seed: 1
model_type: erf
weights_path: #s3://ll-coco/checkpoints/model_weights_00000253.pth
weights_dir: s3://ll-coco/erf/
decode_cfg_path:  s3://ll-coco/codes/configs/decode_cfg.yaml
trans_cfg_path: s3://ll-coco/codes/configs/trans_cfg.json
