data:
  eval_dir:  /media/liulei/Data/cityscapes
  save_dir: /media/liulei/Data/checkpoints/encoder/eval
  dataset: cityscapes
  batch_size: 2
  input_size: (512, 1024)
  num_classes: -1
  subset: val

seed: 1
compound_coef: 3
weights_path: /media/liulei/Data/checkpoints/encoder/efficient_weights_00000051.pth
weights_dir:
decode_cfg_path: ./configs/decode_cfg.yaml
trans_cfg_path: ./configs/trans_cfg.json

