data:
  test_dir: s3://ll-coco/datasets/cityscapes/leftImg8bit/test
  test_image: #C:\data\checkpoints\erf\000000000026.jpg
  save_dir: ./test
  dataset: dir
  batch_size: 1
  num_classes: 8

seed: 1
model_type: erf
weights_path: s3://ll-coco/checkpoints/model_weights_00000214.pth
decode_cfg_path: s3://ll-coco/codes/configs/decode_cfg.yaml
trans_cfg_path: s3://ll-coco/codes/configs/trans_cfg.json
