data:
  test_dir: /media/liulei/Data/cityscapes/leftImg8bit/val
  test_image:
  save_dir: /media/liulei/Data/checkpoints/efficient/test
  dataset: dir
  batch_size: 1
  input_size: (512, 1024)
  num_classes: 8

seed: 1
compound_coef: 3
weights_path: /media/liulei/Data/checkpoints/efficient/efficient_weights_00000039.pth
decode_cfg_path: ./configs/decode_cfg.yaml
trans_cfg_path: ./configs/trans_cfg.json
