data:
  test_dir: D:\cityscapes\leftImg8bit\val
  test_image: #E:\checkpoints\erf\
  save_dir: D:\checkpoints\test
  dataset: dir
  batch_size: 1
  input_size: (512, 1024)
  num_classes: 8

seed: 1
compound_coef: 4
weights_path: D:\checkpoints\efficient\efficient_weights_00000100.pth
decode_cfg_path: .\configs\decode_cfg.yaml
trans_cfg_path: .\configs\trans_cfg.json
