data:
  test_dir: C:\data\cityscapes\leftImg8bit\val
  test_image: #C:\data\checkpoints\erf\000000000026.jpg
  save_dir: C:\data\checkpoints\test
  dataset: dir
  batch_size: 1
  input_size: (512, 1024)
  num_classes: 8

seed: 1
model_type: erf
weights_path: C:\data\checkpoints\erf\erf_weights_00000114.pth
decode_cfg_path: .\configs\decode_cfg.yaml
