data:
  test_dir: E:\cityscapes\leftImg8bit\val
  test_image: #E:\checkpoints\erf\
  save_dir: E:\checkpoints\test
  dataset: dir
  batch_size: 1
  input_size: (512, 1024)
  num_classes: 8

seed: 1
model_type: erf
weights_path: E:\checkpoints\erf2\erf_weights_00000294.pth
decode_cfg_path: .\configs\decode_cfg.yaml
trans_cfg_path: .\configs\trans_cfg.json
