data:
  test_dir: C:\data\cityscapes-simple\leftImg8bit\train
  test_image: #C:\data\checkpoints\erf\000000000026.jpg
  save_dir: C:\data\checkpoints\test
  dataset: dir
  batch_size: 1
  input_size: (512, 1024)
  num_classes: 14

seed: 1
weights_path: C:\data\checkpoints\erf\model_weights_00000214.pth
decode_cfg_path: .\configs\decode_cfg.yaml
