data:
  train_dir:  E:\cityscapes
  save_dir: E:\checkpoints\erf
  dataset: cityscapes
  batch_size: 2
  input_size: (512, 1024)
  num_classes: -1

optimizer:
  lr: 2e-4
  type: Adam
  momentum: 0.9

loss:
  focal_alpha: 2
  focal_beta: 4
  ae_alpha: 0.5
  ae_beta: 1
  ae_delta: 2
  whd_alpha: 0.5
  whd_beta: 2
  kp_threshold: 0.5

max_iter: -1
num_epochs: 2000
save_span: 100
seed: 1
fixed_parts: # ["encoder"]
model_type: erf
pretrained_path: E:\checkpoints\erf1\erf_weights_00000090.pth
decode_cfg_path: .\configs\decode_cfg.yaml
trans_cfg_path: .\configs\trans_cfg.json
start_eval_epoch: 0
