data:
  train_dir:  E:\cityscapes-official
  save_dir: E:\checkpoints\dla
  dataset: cityscapes
  batch_size: 2
  input_size: (512, 1024)
  num_classes: -1
  from_file: True

optimizer:
  lr: 2e-4
  type: Adam
  momentum: 0.9

loss:
  focal_alpha: 2
  focal_beta: 4
  ae_alpha: 0.5
  ae_beta: 1
  ae_delta: 2
  whd_alpha: 0.5
  whd_beta: 2
  kp_threshold: 0.5

max_iter: -1
num_epochs: 2000
save_span: 100
seed: 1
fixed_parts: # ["encoder"]
model_type: dla
pretrained_path: #C:\data\checkpoints\erf\erfnet_encoder_pretrained.pth
decode_cfg_path: .\configs\decode_cfg.yaml
start_eval_epoch: 0
