data:
  train_dir:  s3://hyy-coco/datasets/cityscapes
  val_dir:  s3://hyy-coco/datasets/cityscapes
  save_dir: s3://hyy-coco/checkpoints
  dataset: cityscapes
  batch_size: 8
  input_size: (512, 1024)
  num_classes: -1
  from_file: True

optimizer:
  lr: 2e-4
  type: Adam
  momentum: 0.9

loss:
  focal_alpha: 2
  focal_beta: 4
  ae_alpha: 0.5
  ae_beta: 1
  ae_delta: 2
  whd_alpha: 0.2
  whd_beta: 2
  kp_threshold: 0.4

max_iter: -1
num_epochs: 2000
save_span: 1000
seed: 1
fixed_parts: ["encoder"]
pretrained_path: s3://hyy-coco/checkpoints/erfnet_encoder_pretrained.pth
decode_cfg_path: .\configs\decode_cfg.yaml
start_eval_epoch: 20
